/**
 * MIT License
 * Copyright (c) 2026 Microsoft Corporation
 * See LICENSE in the repository root.
 */

import { BRAND } from "./brand.js";

export interface DefenderP2ReportField {
  key: string;
  label: string;
  value: string;
  help: string;
}

export interface DefenderP2ReportData {
  title: string;
  summary: string;
  preparedFor?: string;
  generatedAt: Date;
  fields: DefenderP2ReportField[];
  aiNarrative?: string;
  sources: { label: string; url: string }[];
}

const LEGAL =
  `Unofficial estimate generated by ${BRAND.name}, a Ninja Paws independent community project. ` +
  "Not affiliated with, endorsed by, or produced by Microsoft. Validate results, licensing, eligibility, pricing, and entitlements with current Microsoft documentation and your Microsoft account team before making decisions. Use at your own risk.";

const COPYRIGHT =
  "Copyright (c) 2026 Microsoft Corporation. Sentinel Optimizer by Ninja Paws. Released under the MIT License.";

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "customer";
}

export async function exportDefenderP2Pdf(data: DefenderP2ReportData): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  const footerTop = pageHeight - 66;
  const navy: [number, number, number] = [36, 58, 94];
  const blue: [number, number, number] = [0, 120, 212];
  const ink: [number, number, number] = [27, 27, 27];
  const grey: [number, number, number] = [95, 95, 95];
  let y = 64;

  function ensureSpace(height: number): void {
    if (y + height > footerTop) {
      doc.addPage();
      y = 64;
    }
  }

  function heading(text: string): void {
    ensureSpace(34);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...navy);
    doc.text(text, margin, y);
    y += 8;
    doc.setDrawColor(...blue);
    doc.setLineWidth(1.5);
    doc.line(margin, y, margin + 48, y);
    y += 18;
  }

  function paragraph(text: string, size = 10, color = ink): void {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentWidth) as string[];
    for (const line of lines) {
      ensureSpace(size + 4);
      doc.text(line, margin, y);
      y += size + 4;
    }
    y += 4;
  }

  function fieldValue(key: string): string {
    return data.fields.find((field) => field.key === key)?.value || "Not provided";
  }

  function table(headers: string[], rows: string[][], widths: number[]): void {
    const padding = 7;
    const lineHeight = 10;

    const drawHeader = (): void => {
      doc.setFillColor(...navy);
      doc.rect(margin, y, contentWidth, 22, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(255, 255, 255);
      let x = margin;
      headers.forEach((header, index) => {
        doc.text(header, x + padding, y + 14);
        x += widths[index];
      });
      y += 22;
    };

    ensureSpace(44);
    drawHeader();
    rows.forEach((row, rowIndex) => {
      const cells = row.map((cell, index) => doc.splitTextToSize(cell, widths[index] - padding * 2) as string[]);
      const rowHeight = Math.max(22, Math.max(...cells.map((cell) => cell.length)) * lineHeight + padding * 2);
      if (y + rowHeight > footerTop) {
        doc.addPage();
        y = 64;
        drawHeader();
      }
      if (rowIndex % 2 === 1) {
        doc.setFillColor(243, 246, 251);
        doc.rect(margin, y, contentWidth, rowHeight, "F");
      }
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(...ink);
      let x = margin;
      cells.forEach((cell, index) => {
        doc.text(cell, x + padding, y + padding + 7);
        x += widths[index];
      });
      y += rowHeight;
    });
    y += 16;
  }

  doc.setFillColor(...navy);
  doc.rect(0, 0, pageWidth, 150, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(21);
  const titleLines = doc.splitTextToSize("Defender for Servers Plan 2", contentWidth) as string[];
  doc.text(titleLines, margin, 58);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.text("Data ingestion benefit estimate", margin, 88);
  doc.setFontSize(9.5);
  doc.setTextColor(180, 215, 245);
  doc.text(`Prepared for: ${data.preparedFor?.trim() || "Customer"}`, margin, 113);
  doc.text(`Generated: ${data.generatedAt.toISOString().slice(0, 10)} UTC`, margin, 129);
  y = 178;

  heading("Executive summary");
  paragraph(data.summary);
  paragraph(
    `The analysis observed ${fieldValue("Nodes")} nodes across ${fieldValue("Workspaces")} workspaces. ` +
      `The conservative estimated benefit is ${fieldValue("RecommendedFreeGBPerDay")} GB/day ` +
      `(${fieldValue("RecommendedFreeGBPerMonth")} GB/month), with ${fieldValue("ConservativeCoveragePct")}% ` +
      "of currently eligible ingestion covered by the modeled allowance.",
  );

  heading("Key findings");
  table(
    ["Measure", "Result"],
    [
      ["Protected nodes observed", fieldValue("Nodes")],
      ["Workspaces analyzed", fieldValue("Workspaces")],
      ["Recommended benefit", `${fieldValue("RecommendedFreeGBPerDay")} GB/day`],
      ["Recommended monthly benefit", `${fieldValue("RecommendedFreeGBPerMonth")} GB/month`],
      ["Recommended annual benefit", `${fieldValue("RecommendedFreeGBPerYear")} GB/year`],
      ["Eligible ingestion covered", `${fieldValue("ConservativeCoveragePct")}%`],
      ["Unused allowance", `${fieldValue("UnusedCapGBPerDay")} GB/day (${fieldValue("UnusedCapPct")}%)`],
    ],
    [contentWidth * 0.62, contentWidth * 0.38],
  );

  if (data.aiNarrative) {
    heading("AI-assisted interpretation");
    paragraph(data.aiNarrative);
    paragraph(
      "This narrative was generated by AI from the supplied result. It can contain errors and does not replace the deterministic values or independent review.",
      8.5,
      grey,
    );
  }

  heading("Detailed results");
  table(
    ["Measure", "Value", "Interpretation"],
    data.fields
      .filter((field) => field.key !== "EligibleTableBreakdown" && field.key !== "WorkspaceBreakdown")
      .map((field) => [field.label, field.value || "Not provided", field.help]),
    [contentWidth * 0.31, contentWidth * 0.22, contentWidth * 0.47],
  );

  heading("Method and limitations");
  paragraph(
    "The report uses the deterministic result produced by the repository's documented KQL. The recommended value uses the conservative eligible-table set and is capped by the modeled 500 MB per node per day allowance. Workspace-level pooling is an approximation where the Usage table cannot reliably map ingestion back to subscription-level allowance pools.",
  );
  paragraph(
    "This is a directional estimate, not a bill, quote, entitlement statement, licensing determination, or proof that Defender for Servers Plan 2 is enabled. Data latency, query scope, permissions, collection method, workspace design, and product changes can materially affect the result.",
  );

  heading("Sources");
  data.sources.forEach((source) => paragraph(`${source.label}: ${source.url}`, 8.5, grey));

  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page++) {
    doc.setPage(page);
    if (page > 1) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...navy);
      doc.text(`${BRAND.name} | Defender for Servers Plan 2 estimate`, margin, 28);
      doc.setDrawColor(210, 220, 232);
      doc.line(margin, 36, pageWidth - margin, 36);
    }
    doc.setDrawColor(210, 220, 232);
    doc.line(margin, footerTop - 6, pageWidth - margin, footerTop - 6);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.2);
    doc.setTextColor(...grey);
    const legalLines = doc.splitTextToSize(`${COPYRIGHT} ${LEGAL}`, contentWidth - 58) as string[];
    doc.text(legalLines.slice(0, 4), margin, footerTop + 5);
    doc.text(`Page ${page} of ${pages}`, pageWidth - margin, pageHeight - 18, { align: "right" });
  }

  const customer = data.preparedFor?.trim() ? `-${slug(data.preparedFor)}` : "";
  doc.save(`defender-p2-benefit${customer}-${data.generatedAt.toISOString().slice(0, 10)}.pdf`);
}